<!DOCTYPE html>
<!--
	Big Picture by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>

<head>
    <title>EHS - Eco Healing Solutions</title>
    <meta charset="utf-8" />
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="assets/css/main.css" />
    <noscript>
        <link rel="stylesheet" href="assets/css/noscript.css" />
    </noscript>
    <style>
        video {
            display: block;
            height: 150%;
            left: 0;
            object-fit: cover;
            position: fixed;
            top: -25%;
            width: 100%;
            z-index: -1;
        }
    </style>
</head>

<body class="is-preload">
    <!-- Header -->
    <header id="header">
        <h1><img src="images/logo2.png" style="height: 100%" /></h1>
        <nav>
            <ul>
                <li><a href="{{ route('welcome') }}">Intro</a></li>
                <li><a href="#contact">Contact</a></li>
                <li><a href="{{ route('about') }}">About</a></li>
                <li><a href="{{ route('login') }}">Log In</a></li>
            </ul>
        </nav>
    </header>

    <!-- Intro -->
    <video src="videos/video-banner.mp4" autoplay loop id="vid" muted></video>
    <script>
        document.getElementById("vid").play();
    </script>
    <section id="intro" class="main style1 dark fullscreen">
        <div class="content" style="background-color: rgba(0, 0, 0, 0.5)">
            <header>
                <h2>
                    We provide the best sustainable strategy to grow up your WEALTH
                </h2>
            </header>
            <p>
                We are is the best option for your company to start receiving passive
                income. Instant Payments, Transparency, Sustainability
            </p>
            <footer>
                <a href="#one" class="button style2 down">More</a>
            </footer>
        </div>
    </section>

    <!-- One -->
    <section id="one" class="main style2 right dark fullscreen">
        <div class="content box style2">
            <header>
                <h2>Know more about EHS</h2>
            </header>
            <p>
                Eco Healing Solutions was founded with a clear vision: to bridge the
                gap between environmental action and financial opportunity.
                Recognizing the growing demand for credible carbon offsets, the
                company partners exclusively with reputable sources to purchase
                verified carbon credit certificates generated by high-impact projects
                like algae farms. These credits, certified to meet global standards,
                are then sold to businesses and individuals aiming to offset their
                carbon footprints.
            </p>
        </div>
        <a href="#two" class="button style2 down anchored">Next</a>
    </section>

    <!-- Two -->
    <section id="two" class="main style2 left dark fullscreen">
        <div class="content box style2">
            <header>
                <h2>Carbon Credits</h2>
            </header>
            <p>
                By investing in our sustainable agriculture company, you’re not just
                supporting eco-friendly farming and responsible land use—you’re also
                entering the crypto world. This innovative approach to finance adds
                transparency and accessibility, making your investment even more
                sustainable and impactful. Together, we can grow wealth, empower
                communities, and nurture the planet while leveraging the power of
                cryptocurrency for a better future.
            </p>
        </div>
        <a href="#work" class="button style2 down anchored">Next</a>
    </section>

    <!--  -->
    <section class="slider">
        <div class="game-section">
            <h2 class="line-title">Positive Impacts of Carbon Credits Trading</h2>
            <div class="owl-carousel custom-carousel owl-theme">
                <div
                    class="item"
                    style="background-image: url(images/slider_10/1.jpg)">
                    <div class="item-desc">
                        <h3>1. Combatting Climate Change</h3>
                        <p>
                            Carbon credits trading directly contributes to reducing
                            greenhouse gas emissions by incentivizing businesses to adopt
                            cleaner technologies and sustainable practices. Every credit
                            represents a tangible step toward a healthier planet.
                        </p>
                    </div>
                </div>
                <div
                    class="item"
                    style="background-image: url(images/slider_10/2.jpg)">
                    <div class="item-desc">
                        <h3>2. Encouraging Innovation</h3>
                        <p>
                            The market for carbon credits fosters innovation by rewarding
                            companies that develop eco-friendly solutions. It drives
                            investment in renewable energy, energy efficiency, and carbon
                            capture technologies.
                        </p>
                    </div>
                </div>
                <div
                    class="item"
                    style="background-image: url(images/slider_10/3.jpg)">
                    <div class="item-desc">
                        <h3>3. Supporting Global Sustainability Goals</h3>
                        <p>
                            Carbon credits align with global sustainability initiatives like
                            the United Nations’ Sustainable Development Goals (SDGs),
                            particularly Goal 13: Climate Action. By trading credits, you
                            are actively participating in a global effort to create a
                            sustainable future.
                        </p>
                    </div>
                </div>
                <div
                    class="item"
                    style="background-image: url(images/slider_10/4.jpg)">
                    <div class="item-desc">
                        <h3>4. Protecting Natural Ecosystems</h3>
                        <p>
                            Many carbon credit projects involve reforestation, conservation,
                            and sustainable land management. These projects not only reduce
                            emissions but also protect biodiversity and enhance ecosystems.
                        </p>
                    </div>
                </div>
                <div
                    class="item"
                    style="background-image: url(images/slider_10/5.jpg)">
                    <div class="item-desc">
                        <h3>5. Generating Economic Benefits</h3>
                        <p>
                            Carbon credit trading opens opportunities for economic growth,
                            particularly in developing regions. Communities benefit from
                            projects that provide jobs, improve infrastructure, and promote
                            sustainable development.
                        </p>
                    </div>
                </div>
                <div
                    class="item"
                    style="background-image: url(images/slider_10/6.jpg)">
                    <div class="item-desc">
                        <h3>6. Empowering Businesses to Go Green</h3>
                        <p>
                            Through carbon credits, companies can offset their emissions and
                            transition to greener operations while achieving compliance with
                            environmental regulations. It’s a cost-effective way to meet
                            sustainability goals.
                        </p>
                    </div>
                </div>
                <div
                    class="item"
                    style="background-image: url(images/slider_10/7.jpg)">
                    <div class="item-desc">
                        <h3>7. Promoting Transparency and Accountability</h3>
                        <p>
                            Carbon markets operate under rigorous standards with verified
                            and traceable credits, ensuring integrity and transparency. This
                            builds trust and encourages participation in climate-positive
                            activities.
                        </p>
                    </div>
                </div>
                <div
                    class="item"
                    style="background-image: url(images/slider_10/8.jpg)">
                    <div class="item-desc">
                        <h3>8. Engaging Individuals and Organizations</h3>
                        <p>
                            Carbon credits allow not just businesses but also individuals to
                            contribute to global climate solutions. Purchasing credits is a
                            direct way to offset personal or corporate carbon footprints.
                        </p>
                    </div>
                </div>
                <div
                    class="item"
                    style="background-image: url(images/slider_10/9.jpg)">
                    <div class="item-desc">
                        <h3>9. Creating a Competitive Advantage</h3>
                        <p>
                            Participating in carbon credit trading can enhance a company’s
                            reputation as a leader in sustainability. It demonstrates
                            corporate responsibility and appeals to environmentally
                            conscious customers and stakeholders.
                        </p>
                    </div>
                </div>
                <div
                    class="item"
                    style="background-image: url(images/slider_10/10.jpg)">
                    <div class="item-desc">
                        <h3>10. Driving a Low-Carbon Economy</h3>
                        <p>
                            By placing a financial value on carbon emissions, carbon credits
                            drive a shift toward a low-carbon economy, paving the way for
                            long-term environmental and economic resilience.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--  -->

    <!-- Work -->
    <section id="work" class="main style3 primary">
        <div class="content">
            <header>
                <h2>News</h2>
                <p>
                    Welcome to the News section of our website, where we keep you
                    updated with the latest developments, insights, and announcements in
                    our industry and beyond.
                    <br />
                    What You'll Find Here:<br />
                    Breaking News: Stay informed with up-to-date reports on key events
                    and trends shaping our field.<br />
                    Insights & Analysis: Dive into expert commentary and in-depth
                    articles exploring the implications of recent changes in policies,
                    technologies, and market dynamics.<br />
                    Success Stories: Celebrate milestones and achievements within our
                    community, showcasing the impact of innovation and collaboration.<br />
                    Events & Announcements: Keep track of upcoming events, product
                    launches, and special initiatives.
                </p>
            </header>

            <!-- Gallery  -->
            <div class="gallery">
                <article class="from-left">
                    <a href="images/fulls/01.jpg" class="image fit"><img src="images/thumbs/01.jpg" title="The Anonymous Red" alt="" /></a>
                </article>
                <article class="from-right">
                    <a href="images/fulls/02.jpg" class="image fit"><img src="images/thumbs/02.jpg" title="Airchitecture II" alt="" /></a>
                </article>
                <!-- <article class="from-left">
            <a href="images/fulls/03.jpg" class="image fit"
              ><img src="images/thumbs/03.jpg" title="Air Lounge" alt=""
            /></a>
          </article>
          <article class="from-right">
            <a href="images/fulls/04.jpg" class="image fit"
              ><img src="images/thumbs/04.jpg" title="Carry on" alt=""
            /></a>
          </article>
          <article class="from-left">
            <a href="images/fulls/05.jpg" class="image fit"
              ><img
                src="images/thumbs/05.jpg"
                title="The sparkling shell"
                alt=""
            /></a>
          </article>
          <article class="from-right">
            <a href="images/fulls/06.jpg" class="image fit"
              ><img src="images/thumbs/06.jpg" title="Bent IX" alt=""
            /></a>
          </article>-->
            </div>
        </div>
    </section>

    <!-- Contact -->
    <section id="contact" class="main style3 secondary">
        <div class="content">
            <header>
                <h2>Contact Us.</h2>
                <p>

                </p>
            </header>
            <div class="box">
                <form method="post" action="#">
                    <div class="fields">
                        <div class="field half">
                            <input type="text" name="name" placeholder="Name" />
                        </div>
                        <div class="field half">
                            <input type="email" name="email" placeholder="Email" />
                        </div>
                        <div class="field">
                            <textarea
                                name="message"
                                placeholder="Message"
                                rows="6"></textarea>
                        </div>
                    </div>
                    <ul class="actions special">
                        <li><input type="submit" value="Send Message" /></li>
                    </ul>
                </form>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer id="footer">
        <!-- Icons -->
        <ul class="icons">
            <li>
                <a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a>
            </li>
            <li>
                <a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a>
            </li>
            <li>
                <a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a>
            </li>
            <li>
                <a href="#" class="icon brands fa-linkedin-in"><span class="label">LinkedIn</span></a>
            </li>
            <li>
                <a href="#" class="icon brands fa-dribbble"><span class="label">Dribbble</span></a>
            </li>
            <li>
                <a href="#" class="icon brands fa-pinterest"><span class="label">Pinterest</span></a>
            </li>
        </ul>

        <!-- Menu -->
        <ul class="menu">
            <li>&copy;</li>
            <li>Eco Healing Solutions</li>
        </ul>
    </footer>

    <!-- Scripts -->
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/jquery.poptrox.min.js"></script>
    <script src="assets/js/jquery.scrolly.min.js"></script>
    <script src="assets/js/jquery.scrollex.min.js"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.js"
        integrity="sha512-gY25nC63ddE0LcLPhxUJGFxa2GoIyA5FLym4UJqHDEMHjp8RET6Zn/SHo1sltt3WuVtqfyxECP38/daUc/WVEA=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer"></script>
    <script src="assets/js/browser.min.js"></script>
    <script src="assets/js/breakpoints.min.js"></script>
    <script src="assets/js/util.js"></script>
    <script src="assets/js/main.js"></script>
</body>

</html>
